// @flow
export const UserConstant = {
  PROFILE_SAVE_REQUEST: 'PROFILE_SAVE_REQUEST',
  PROFILE_SAVE_REQUEST_SUCCESS: 'PROFILE_SAVE_REQUEST_SUCCESS',
  PROFILE_SAVE_REQUEST_FAILED: 'PROFILE_SAVE_REQUEST_FAILED',
  PROFILE_REQUEST_SAVED: 'PROFILE_REQUEST_SAVED',

  USER_NAME_KEY: 'USER_NAME',
  USER_FULL_NAME_KEY: 'FULL_NAME',
  USER_PASSWORD_KEY: 'PASSWORD',
};
