// @flow
export const HomeConstant = {
  NEWS_REQUEST: 'NEWS_REQUEST',
  NEWS_REQUEST_SUCCESS: 'NEWS_REQUEST_SUCCESS',
  NEWS_REQUEST_FAILED: 'NEWS_REQUEST_FAILED',
  NEWS_PULL_TO_REFRESH: 'NEWS_PULL_TO_REFRESH',
  LOAD_MORE_NEWS: 'LOAD_MORE_NEWS',
  NEWS_LOAD_MORE_REQUEST: 'NEWS_LOAD_MORE_REQUEST',
  NEWS_LOAD_MORE_REQUEST_SUCCESS: 'NEWS_LOAD_MORE_REQUEST_SUCCESS',
  NEWS_ARTICLES_PAGE_SIZE: 20,
};
