// @flow
export const CustomNewsConstant = {
  CUSTOM_NEWS_REQUEST: 'CUSTOM_NEWS_REQUEST',
  CUSTOM_NEWS_REQUEST_SUCCESS: 'CUSTOM_NEWS_REQUEST_SUCCESS',
  CUSTOM_NEWS_REQUEST_FAILED: 'CUSTOM_NEWS_REQUEST_FAILED',
};
